version: '3.3'
services:

  frontend:
    image: alectyp/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - frontend

  backend:
    image: alectyp/backend:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media_backend/
    depends_on:
      - frontend
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0:8000"

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media_backend/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  postgres_db: